### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by memark** [actually-reb/uiua-sokoban#1]
I'm super curious about this game implementation!

Any chance you could update the code to work with current Uiua version?

<img width="998" alt="image" src="https://github.com/actually-reb/uiua-sokoban/assets/318504/a4036d24-507c-436b-b7a9-dfe41516456d">

**Comment by rebca-online** [comment]
Oh sure! Thank you for your interest :) This is an easy fix, just need to replace the outdated bind symbols with parenthesis, and replacing the old style if statements.

**Comment by rebca-online** [comment]
Turns out there are a lot of things that I'm realizing were changed. Shocks me at how fast this language is moving.

**Comment by memark** [comment]
@actually-reb Thanks!

Sorry for my late follow-up here, but I'm afraid I'm getting another error now
```
Error: Cannot add shape [6 × 9] row to array with shape [7 × 6] rows
                                                                      at main.ua:4:4
                                                                                    4 |   ⊐∵(↘1⬚@ ⊜∘≠,@\n)
                                                                                                                 ─
                                                                                                                    in fn from main.ua:4:4 at main.ua:4:3
```
